AWSTemplateFormatVersion: '2010-09-09'
Description: Create EventBridge Rule and SQS Queue

Resources:
  MySqsQueue:
    Type: AWS::SQS::Queue

  MyEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "EventRule"
      EventPattern:
        source:
          - "custom.event"
      ScheduleExpression: "rate(30 seconds)"
      State: ENABLED
      Targets:
        - Arn: !GetAtt MySqsQueue.Arn
          Id: "SQSqueue"

Outputs:
  SQSqueueName:
    Description: SQS queue name
    Value: !GetAtt MySqsQueue.QueueName

  SQSqueueARN:
    Description: SQS queue ARN
    Value: !GetAtt MySqsQueue.Arn
